[project]
name = "nightingale"
version = "0.0.1"
readme = "README.rst"
description = "An ETL to transform US cities procurement data into OCDS format."
#description-file = "README.rst"
authors = [
    { name = "Open Contracting Partnership", email = "data@open-contracting.org" },
]

classifiers = [
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]


[project.license]
file = "LICENSE"

[project.scripts]
nightingale = "nightingale.cli:run"

[project.urls]
Documentation = "https://github.com/open-contracting/nightingale"
Source = "https://github.com/open-contracting/nightingale"

[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[tool.pylint.BASIC]
good-names = 'e,f,i,n,io' # exception, file, enumerate, number

[tool.pylint.'MESSAGES CONTROL']
disable = [
    'too-many-arguments',
    # Defer to flake8
    'line-too-long',
    # Defer to pydocstyle
    'missing-module-docstring',
    'missing-class-docstring',
    'missing-function-docstring',
]

[tool.setuptools]
packages = ["nightingale"]
