name: Deploy
on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed
jobs:
  docker:
    if: github.event.workflow_run.conclusion == 'success'
    uses: open-contracting/.github/.github/workflows/docker-single.yml@main
    permissions:
      packages: write
